// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dcpmykhxysvxnpgmlyli.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRjcG15a2h4eXN2eG5wZ21seWxpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2MDc0MDcsImV4cCI6MjA4NzE4MzQwN30.5D9o4c4lEkUJPNeltBOAkCZQlPwEAl1o8t7ddInzkJY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});